/* Modelagem Básica
ENTIDADE = TABELA
CAMPOS= ATRIBUTOS	*/

CLIENTE

NOME - CARACTERES(30)
CPF - NUMERICO(11)
EMAIL - CARACTERES(30)
TELEFONE - CARACTER(30)
ENDERECO - CARACTER(100)
SEXO - CARACTER(1)

/* PROCESSOS DE MODELAGEM */

/* FASE 01 E FASE 02 - FEITAS PELO AD (ADMINISTRADOR DE DADOS) */

MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

/* FASE 03 - FEITAS PELO DBA/AD */
MODELAGEM FÍSICA - SCRIPTS DE BANCO

/* INICIANDO A MODELAGEM FÍSICA */

/* CRIANDO BANCO DE DADOS */
CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO */
USE PROJETO;

/* CRIANDO A TABELA DE CLIENTE */
CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);

/* VERIFICANDO TABELAS */
SHOW TABLES;

/* DESCOBRINDO COMO É A ESTRUTURA DA TABELA */
DESC CLIENTE;