INSERT INTO CLIENTE(NOME, SEXO, ENDERECO, TELEFONE, CPF, EMAIL) VALUES('ALAN', 'M', 'RUA TOLEDO - PERIOLO - CASCAVEL - PR',  '45998065041', 097667389, 'ALAN@GMAIL.COM');

/* O COMANDO SELECT
seleção projeção e junção
*/

/* ALIAS DE COLUNAS */
/* AS DA NOME A COLUNA PROJETADA */

SELECT NOW() AS DATA_HORA, 'ALAN LEONARDO' AS ALUNO;

SELECT 'ALAN LEONARDO';

SELECT 'BANCO DE DADOS';

SELECT NOME AS CLIENTE, SEXO, EMAIL, ENDERECO FROM CLIENTE;

SELECT NOME AS CLIENTE, SEXO, EMAIL, ENDERECO, NOW() AS DATA_HORA FROM CLIENTE;

/* APENAS PARA FIM ACADEMICO */
SELECT * FROM CLIENTE;