/* FILTROS DE SELEÇÃO*/
SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, ENDERECO FROM CLIENTE
WHERE SEXO = 'M';

/* UTILIZANDO LIKE PRA ENCONTRAR UMA INFORMAÇÃO ESPECIFICA DO CAMPO*/
SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE 'PR';

/* CARACTER CORINGA % - IDENTIFICA O TERMO ESPECIFICO INDEPENDENTE DA POSIÇÃO*/
SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%PR%';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%_____PR_____%';