USE LIVRARIA;

/* OPERADORES LÓGICOS 
OR - PARA QUE A SAÍDA DA QUERY SER VERDADEIRA, BASTA QUE APENAS UMA CONDIÇÃO SEJA VERDADEIRA
AND - PARA QUE A SAÍDA DA QUERY SER VERDADEIRA, TODAS AS CONDIÇÕES PRECISAM SER VERDADEIRAS
% - BUSCA INFORMAÇÕES NOS CAMPOS INDEPENDENTE DA POSIÇÃO QUE OS DADOS ESTÃO
*/

SELECT *
FROM LIVROS
WHERE SEXO_AUTOR = 'Masculino'
AND (UF_EDITORA = 'SP' OR UF_EDITORA = 'RJ');

SELECT *
FROM LIVROS
WHERE SEXO_AUTOR = 'Masculino'
AND UF_EDITORA LIKE 'SP';