USE PROJETO;

/* CONTAGEM DA QUANTIDADE DE REGISTROS*/ 
SELECT COUNT(*) AS "QUANTIDADES DE REGISTROS"
FROM CLIENTE;

/* OPERADOR GROUP BY */
SELECT SEXO, COUNT(*)
FROM CLIENTE
GROUP BY SEXO;

/* PERFORMANCE COM OPERADORES LOGICOS 
OR / AND = SEMPRE COLOCAR AS PRIMEIRAS CONDIÇÕES COM MAIS CHANCES DE SEREM VERDADEIRAS, POIS IRÁ MELHORAR A PERFORMANCE
*/
SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE SEXO = 'F'
OR CIDADE = 'CASCAVEL';

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE CIDADE = 'CASCAVEL'
AND SEXO = 'F';