/* ATUALIZANDO REGISTROS NA TABELA 
Sempre use o SELECT pra confirmar quais informações serão atualizadas
*/ 

SELECT *
FROM CLIENTE;

UPDATE CLIENTE
SET EMAIL = 'ALANLEONARDO@GMAIL.COM';

SELECT *
FROM CLIENTE
WHERE NOME = ALAN;

UPDATE CLIENTE
SET EMAIL = 'ALANLEONARDO@GMAIL.COM'
WHERE NOME = 'ALAN';
