/* DELETANDO REGISTROS NA TABELA 
Sempre use o SELECT pra confirmar quais informações serão DELETADAS
*/

SELECT COUNT(*)
FROM CLIENTE
WHERE NOME = 'ALAN';

SELECT * 
FROM CLIENTE
WHERE NOME = 'ALAN';

DELETE 
FROM CLIENTE
WHERE NOME = 'ALAN';

SELECT * FROM CLIENTE
WHERE NOME = 'ALISSON'
AND CPF IS NULL;

DELETE FROM CLIENTE