/* SELECAO E PROJECAO */

/* PROJECAO --> É TUDO QUE VOCE VER NA TELA */
SELECT NOW() AS DATA_ATUAL;

SELECT 2 + 2 AS SOMA;

SELECT 2 + 2 AS SOMA, NOME, NOW()
FROM CLIENTE;


/* SELECAO --> É UM SUBCONJUNTO TOTAL DE REGISTROS DE UMA TABELA 
A- CLAUSULA DE SELECAO É O WHERE */
SELECT NOME, SEXO, EMAIL /* PROJEÇÃO */
FROM CLIENTE /* ORIGEM */
WHERE SEXO = 'F'; /* SELEÇÃO */

SELECT NUMERO /* PROJEÇÃO */
FROM TELEFONE /* ORIGEM */
WHERE TIPO = 'CEL'; /* SELEÇÃO */