/*
EXISTEM VÁRIAS CATEGORIAS DE CÓDIGOS
DML - DATA MANIPULATION LANGUAGE
DDL - DATA DEFINITION LANGUAGE
DCL - DATA CONTROL LANGUAGE
TCL - TRANSACTION CONTROL LANGUAGE */

/*  COMANDOS DE DML */

/* INSERT */
INSERT INTO CLIENTE 
	VALUES(NULL, 'PAULA', 'M',NULL, '87321287500');

SELECT *
FROM CLIENTE
WHERE NOME = 'PAULA';

INSERT INTO ENDERECO 
	VALUES(NULL, 'RUA JOAQUIM SILVA', 'ALVORADA', 'NITEROI', 'RJ', 7);

INSERT INTO TELEFONE
	VALUES(NULL, 'CEL', '88093212', 7);

/* FILTROS */

SELECT *
FROM CLIENTE
WHERE IDCLIENTE = 7;

/* UPDATE */
UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE = 7;

/* DELETE */
INSERT INTO CLIENTE 
	VALUES(NULL, 'xxxxxxxx', 'M',NULL, 'xxxxxxxx');

SELECT *
FROM CLIENTE;

DELETE
FROM CLIENTE
WHERE IDCLIENTE = 8;