/* DDL - DATA DEFINITION LANGUAGE */

CREATE TABLE PRODUTOS(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOMEPRODUTO VARCHAR(30) NOT NULL,
	PRECO INT,
	FREETE FLOAT(10,2) NOT NULL
);

/* ALTER TABLE 
ALTERANDO O NOME DE UMA COLUNA - CHANGE */
ALTER TABLE PRODUTOS
CHANGE PRECO VALORUNITARIO INT NOT NULL;

DESC PRODUTOS;

ALTER TABLE PRODUTOS
CHANGE VALORUNITARIO VALOR_UNITARIO INT;

ALTER TABLE PRODUTOS
CHANGE FREETE FRETE FLOAT(10,2) NOT NULL;

ALTER TABLE PRODUTOS
CHANGE NOMEPRODUTO NOME_PRODUTO VARCHAR(30) NOT NULL;

DESC PRODUTOS;

/* ALTERANDO O NOME DA TABELA */
RENAME TABLE PRODUTOS TO PRODUTO;

/* MODIFY - ALTERANDO O TIPO */
ALTER TABLE PRODUTOS
MODIFY VALOR_UNITARIO VARCHAR(50) NOT NULL;

/* ADICIONANDO COLUNAS */
ALTER TABLE PRODUTOS
ADD PESO FLOAT(10,2) NOT NULL;

DESC PRODUTOS;

/* APAGANDO UMA COLUNA */
ALTER TABLE PRODUTOS
DROP COLUMN PESO;

DESC PRODUTOS;

/* ADICIONANDO UMA COLUNA NA ORDEM ESPECIFICADA */
ALTER TABLE PRODUTOS
ADD COLUMN PESO FLOAT(10,2) NOT NULL
AFTER NOME_PRODUTO;

ALTER TABLE PRODUTOS
DROP COLUMN PESO;

ALTER TABLE PRODUTOS
ADD COLUMN PESO FLOAT(10,2) NOT NULL
FIRST;

ALTER TABLE PRODUTOS
DROP COLUMN PESO;

ALTER TABLE PRODUTOS
ADD COLUMN PESO FLOAT(10,2) NOT NULL
AFTER NOME_PRODUTO;
