/* ALTERANDO TABELAS */

CREATE TABLE TABELA(
	COLUNA1 VARCHAR(30),
	COLUNA2 VARCHAR(30),
	COLUNA3 VARCHAR(30)
);

/* ADICIONANDO UMA COLUNA COMO PRIMARY KEY */

ALTER TABLE TABELA
ADD PRIMARY KEY(COLUNA1);

/* ADICIONANDO UMA COLUNA SEM POSICAO */
ALTER TABLE TABELA
ADD COLUNA VARCHAR(30);

ALTER TABLE TABELA
ADD COLUNA100 VARCHAR(30);

/* ADICIONANDO UMA COLUNA COM POSICAO ESPECIFICA */
ALTER TABLE TABELA
ADD COLUMN COLUNA4 VARCHAR(30) NOT NULL UNIQUE
AFTER COLUNA3;

/* MODIFICANDO O TIPO DE UM CAMPO */
ALTER TABLE TABELA
MODIFY COLUNA100 INT;

ALTER TABLE TABELA
MODIFY COLUNA2 DATE NOT NULL;

/* RENOMEANDO O NOME DA TABELA */
ALTER TABLE TABELA
RENAME PESSOA;

DESC PESSOA;

/* MAIS UM EXEMPLO */
CREATE TABLE TIME(
	IDTIME INT PRIMARY KEY AUTO_INCREMENT,
	TIME VARCHAR(30),
	ID_PESSOA VARCHAR(30)
);

/* ADICIONANDO FOREIGN KEY */
ALTER TABLE TIME
ADD FOREIGN KEY(ID_PESSOA)
REFERENCES PESSOA(COLUNA1);

/* VERIFICAR AS CHAVES */
SHOW CREATE TABLE TIME;