/* EXERCICIO 
1. CRIE UM BANCO DE DADO CHAMADO PROJETO E CONECTE A ELE
2. CADASTRAR OS CARROS (APENAS 1 POR DONO), NOME DO DONO, NOME DO CARRO, MARCA DO CARRO, PLACA, NOME DO SERVIÇO, DATA DE ENTRADA
4. CADASTRAR AS CORES DOS CARROS - PODE TER MAIS DE UMA COR
5. CADASTRAR OS TELEFONES DOS CLIENTES, MAS NÃO SÃO OBRIGATORIOS
*/

DROP DATABASE PROJETO;

CREATE DATABASE PROJETO;

USE PROJETO;

CREATE TABLE CLIENTES(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	ID_CARRO INT UNIQUE
);
DESC CLIENTES;
+-----------+---------------+------+-----+---------+----------------+
| Field     | Type          | Null | Key | Default | Extra          |
+-----------+---------------+------+-----+---------+----------------+
| IDCLIENTE | int(11)       | NO   | PRI | NULL    | auto_increment |
| NOME      | varchar(30)   | NO   |     | NULL    |                |
| SEXO      | enum('M','F') | NO   |     | NULL    |                |
| ID_CARRO  | int(11)       | YES  | UNI | NULL    |                |
+-----------+---------------+------+-----+---------+----------------+

CREATE TABLE TELEFONES(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('CEL','RES','COM') NOT NULL,
	TELEFONE VARCHAR(30) NOT NULL,
	ID_CLIENTE INT
);
DESC TELEFONES;
+------------+-------------------------+------+-----+---------+----------------+
| Field      | Type                    | Null | Key | Default | Extra          |
+------------+-------------------------+------+-----+---------+----------------+
| IDTELEFONE | int(11)                 | NO   | PRI | NULL    | auto_increment |
| TIPO       | enum('CEL','RES','COM') | NO   |     | NULL    |                |
| TELEFONE   | varchar(30)             | NO   |     | NULL    |                |
| ID_CLIENTE | int(11)                 | YES  | MUL | NULL    |                |
+------------+-------------------------+------+-----+---------+----------------+

CREATE TABLE MARCAS(
	IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
	MARCA VARCHAR(30) UNIQUE
);
DESC MARCAS;
+---------+-------------+------+-----+---------+----------------+
| Field   | Type        | Null | Key | Default | Extra          |
+---------+-------------+------+-----+---------+----------------+
| IDMARCA | int(11)     | NO   | PRI | NULL    | auto_increment |
| MARCA   | varchar(30) | YES  | UNI | NULL    |                |
+---------+-------------+------+-----+---------+----------------+

CREATE TABLE CARROS(
	IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
	MODELO VARCHAR(30) NOT NULL,
	PLACA VARCHAR(30) NOT NULL UNIQUE,
	ID_MARCA INT
);
DESC CARROS;
+----------+-------------+------+-----+---------+----------------+
| Field    | Type        | Null | Key | Default | Extra          |
+----------+-------------+------+-----+---------+----------------+
| IDCARRO  | int(11)     | NO   | PRI | NULL    | auto_increment |
| MODELO   | varchar(30) | NO   |     | NULL    |                |
| PLACA    | varchar(30) | NO   | UNI | NULL    |                |
| ID_MARCA | int(11)     | YES  |     | NULL    |                |
+----------+-------------+------+-----+---------+----------------+

CREATE TABLE CORES(
	IDCOR INT PRIMARY KEY AUTO_INCREMENT,
	COR VARCHAR(30) NOT NULL UNIQUE
);
DESC CORES;
+-------+-------------+------+-----+---------+----------------+
| Field | Type        | Null | Key | Default | Extra          |
+-------+-------------+------+-----+---------+----------------+
| IDCOR | int(11)     | NO   | PRI | NULL    | auto_increment |
| COR   | varchar(30) | NO   | UNI | NULL    |                |
+-------+-------------+------+-----+---------+----------------+

CREATE TABLE CARROS_CORES(
	ID_CARRO INT,
	ID_COR INT,
	PRIMARY KEY(ID_CARRO, ID_COR)
);
DESC CARROS_CORES;
+----------+---------+------+-----+---------+-------+
| Field    | Type    | Null | Key | Default | Extra |
+----------+---------+------+-----+---------+-------+
| ID_CARRO | int(11) | NO   | PRI | NULL    |       |
| ID_COR   | int(11) | NO   | PRI | NULL    |       |
+----------+---------+------+-----+---------+-------+

/* CONSTRAINTS */

ALTER TABLE CLIENTES
ADD CONSTRAINT FK_CARROS_CLIENTES
FOREIGN KEY(ID_CARRO) REFERENCES CARROS(IDCARRO);

ALTER TABLE TELEFONES
ADD CONSTRAINT FK_CLIENTES_TELEFONES
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(IDCLIENTE);

ALTER TABLE CARROS
ADD CONSTRAINT FK_MARCAS_CARROS
FOREIGN KEY(ID_MARCA) REFERENCES MARCAS(IDMARCA);

ALTER TABLE CARROS_CORES
ADD CONSTRAINT FK_CARRO
FOREIGN KEY(ID_CARRO) REFERENCES CARROS(IDCARRO);

ALTER TABLE CARROS_CORES
ADD CONSTRAINT FK_COR
FOREIGN KEY(ID_COR) REFERENCES CORES(IDCOR);

SHOW CREATE TABLE CLIENTES;
SHOW CREATE TABLE TELEFONES;
SHOW CREATE TABLE MARCAS;
SHOW CREATE TABLE CARROS;
SHOW CREATE TABLE CORES;
SHOW CREATE TABLE CARROS_CORES;

/* INSERIR DADOS DE 10 CLIENTES */

INSERT INTO MARCAS VALUES(NULL, 'FORD');
INSERT INTO MARCAS VALUES(NULL, 'CHEVROLET');
INSERT INTO MARCAS VALUES(NULL, 'MITSUBISHI');
INSERT INTO MARCAS VALUES(NULL, 'FERRARI');
INSERT INTO MARCAS VALUES(NULL, 'LAMBORGHINI');
INSERT INTO MARCAS VALUES(NULL, 'HONDA');
INSERT INTO MARCAS VALUES(NULL, 'FIAT');
INSERT INTO MARCAS VALUES(NULL, 'DODGE');
INSERT INTO MARCAS VALUES(NULL, 'VOLKSWAGEN');
INSERT INTO MARCAS VALUES(NULL, 'SUBARU');

INSERT INTO CARROS VALUES(NULL, 'MUSTANG', 'AAA0001', 1);
INSERT INTO CARROS VALUES(NULL, 'CAMARO', 'BBB0001', 2);
INSERT INTO CARROS VALUES(NULL, 'LANCER EVO', 'CCC0001', 3);
INSERT INTO CARROS VALUES(NULL, 'ENZO', 'DDD0001', 4);
INSERT INTO CARROS VALUES(NULL, 'MURCIELAGO', 'EEE0001', 5);
INSERT INTO CARROS VALUES(NULL, 'S2000', 'FFF0001', 6);
INSERT INTO CARROS VALUES(NULL, 'UNO', 'GGG0001', 7);
INSERT INTO CARROS VALUES(NULL, 'VIPER', 'HHH0001', 8);
INSERT INTO CARROS VALUES(NULL, 'GOL', 'III0001', 9);
INSERT INTO CARROS VALUES(NULL, 'IMPREZA', 'JJJ0001', 10);

INSERT INTO CLIENTES VALUES(NULL, 'ALAN LEONARDO', 'M', 1);
INSERT INTO CLIENTES VALUES(NULL, 'ALBATROX18', 'M', 2);
INSERT INTO CLIENTES VALUES(NULL, 'SHAKAL', 'M', 3);
INSERT INTO CLIENTES VALUES(NULL, 'LUCY SHADE', 'F', 4);
INSERT INTO CLIENTES VALUES(NULL, 'OFFCELL', 'M', 5);
INSERT INTO CLIENTES VALUES(NULL, 'ROSA PIMENTA', 'F', 6);
INSERT INTO CLIENTES VALUES(NULL, 'APARECIDA BASTILINA', 'F', 7);
INSERT INTO CLIENTES VALUES(NULL, 'ALISSON ROCHA', 'M', 8);
INSERT INTO CLIENTES VALUES(NULL, 'YURI', 'M', 9);
INSERT INTO CLIENTES VALUES(NULL, 'JULIANE', 'F', 10);

INSERT INTO TELEFONES VALUES(NULL, 'CEL', '998065041', 1);
INSERT INTO TELEFONES VALUES(NULL, 'RES', '32293734', 1);
INSERT INTO TELEFONES VALUES(NULL, 'RES', '32243333', 2);
INSERT INTO TELEFONES VALUES(NULL, 'CEL', '998320932', 3);
INSERT INTO TELEFONES VALUES(NULL, 'RES', '32223131', 4);
INSERT INTO TELEFONES VALUES(NULL, 'COM', '32203939', 4);
INSERT INTO TELEFONES VALUES(NULL, 'COM', '33334444', 5);
INSERT INTO TELEFONES VALUES(NULL, 'RES', '32293734', 7);
INSERT INTO TELEFONES VALUES(NULL, 'COM', '32214144', 7);
INSERT INTO TELEFONES VALUES(NULL, 'CEL', '988932123', 8);
INSERT INTO TELEFONES VALUES(NULL, 'COM', '42222299', 9);
INSERT INTO TELEFONES VALUES(NULL, 'RES', '32219832', 9);
INSERT INTO TELEFONES VALUES(NULL, 'CEL', '988739812', 9);
INSERT INTO TELEFONES VALUES(NULL, 'RES', '32293734', 10);

INSERT INTO CORES VALUES(NULL, 'PRETO');
INSERT INTO CORES VALUES(NULL, 'VERMELHO');
INSERT INTO CORES VALUES(NULL, 'AZUL');
INSERT INTO CORES VALUES(NULL, 'BRANCO');
INSERT INTO CORES VALUES(NULL, 'AMARELO');
INSERT INTO CORES VALUES(NULL, 'AZUL PETROLEO');
INSERT INTO CORES VALUES(NULL, 'CINZA');
INSERT INTO CORES VALUES(NULL, 'MARROM');
INSERT INTO CORES VALUES(NULL, 'PRATA');
INSERT INTO CORES VALUES(NULL, 'BORDO');

INSERT INTO CARROS_CORES VALUES(1, 1);
INSERT INTO CARROS_CORES VALUES(1, 2);
INSERT INTO CARROS_CORES VALUES(2, 1);
INSERT INTO CARROS_CORES VALUES(3, 1);
INSERT INTO CARROS_CORES VALUES(3, 6);
INSERT INTO CARROS_CORES VALUES(4, 4);
INSERT INTO CARROS_CORES VALUES(5, 3);
INSERT INTO CARROS_CORES VALUES(6, 5);
INSERT INTO CARROS_CORES VALUES(7, 1);
INSERT INTO CARROS_CORES VALUES(8, 9);
INSERT INTO CARROS_CORES VALUES(9, 9);
INSERT INTO CARROS_CORES VALUES(9, 7);
INSERT INTO CARROS_CORES VALUES(10, 1);
INSERT INTO CARROS_CORES VALUES(10, 8);