/* CRIAÇÃO E INSERÇÃO DOS DADOS */
SHOW DATABASES;
STATUS
CREATE DATABASE LIVRARIA;
USE LIVRARIA;
CREATE TABLE LIVROS(
	NOME_LIVRO VARCHAR(30),
	NOME_AUTOR VARCHAR(30),
	SEXO_AUTOR CHAR(1),
	NUMERO_PAGINAS INT(4),
	NOME_EDITORA VARCHAR(30),
	VALOR_LIVRO FLOAT(6,2),
	UF_EDITORA CHAR(2),
	ANO_PUBLICACAO INT(4)
);
SHOW TABLES;
DESC LIVROS;

ALTER TABLE LIVROS MODIFY COLUMN SEXO_AUTOR VARCHAR(30);

INSERT INTO LIVROS (NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, UF_EDITORA, ANO_PUBLICACAO)
VALUES ('Cavaleiro Real', 'Ana Claudia', 'Feminino', '465', 'Atlas', '49.90', 'RJ', '2009');

INSERT INTO LIVROS (NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, UF_EDITORA, ANO_PUBLICACAO)
VALUES ('SQL para leigos', 'João Nunes', 'Masculino', '450', 'Addison',	'98.00', 'SP', '2018');

INSERT INTO LIVROS (NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, UF_EDITORA, ANO_PUBLICACAO)
VALUES ('Receitas Caseiras', 'Celia Tavares', 'Feminino', '210', 'Atlas', '45.00', 'RJ', '2008');

INSERT INTO LIVROS (NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, UF_EDITORA, ANO_PUBLICACAO)
VALUES ('Pessoas Efetivas', 'Eduardo Santos', 'Masculino', '390', 'Beta', '78.99', 'RJ', '2018');

INSERT INTO LIVROS (NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, UF_EDITORA, ANO_PUBLICACAO)
VALUES ('Habitos Saudáveis', 'Eduardo Santos', 'Masculino', '630', 'Beta', '150.98', 'RJ', '2019');

INSERT INTO LIVROS (NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, UF_EDITORA, ANO_PUBLICACAO)
VALUES ('A Casa Marrom', 'Hermes Macedo', 'Masculino', '250', 'Bubba', '60.00',	'MG', '2016');

INSERT INTO LIVROS (NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, UF_EDITORA, ANO_PUBLICACAO)
VALUES ('Estacio Querido', 'Geraldo Francisco',	'Masculino', '310', 'Insignia', '100.00', 'ES',	'2015');

INSERT INTO LIVROS (NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, UF_EDITORA, ANO_PUBLICACAO)
VALUES ('Pra sempre amigas', 'Leda Silva', 'Feminino', '510', 'Insignia', '78.98', 'ES', '2011');

INSERT INTO LIVROS (NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, UF_EDITORA, ANO_PUBLICACAO)
VALUES ('Copas Inesqueciveis', 'Marco Alcantara', 'Masculino', '200', 'Larson', '130.98', 'RS', '2018');

INSERT INTO LIVROS (NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGINAS, NOME_EDITORA, VALOR_LIVRO, UF_EDITORA, ANO_PUBLICACAO)
VALUES ('O poder da mente',	'Clara Mafra', 'Feminino', '120', 'Continental', '56.58','SP', '2017');

/* PROJEÇÕES E CONSULTAS */
/* Trazer todos os dados */
SELECT * FROM LIVROS;

/*Trazer o nome do livro e o nome da editora*/
SELECT NOME_LIVRO, NOME_EDITORA
FROM LIVROS;

/*Trazer o nome do livro e a UF dos livros publicados por autores do sexo masculino*/
SELECT NOME_LIVRO, UF_EDITORA 
FROM LIVROS
WHERE SEXO_AUTOR = 'Masculino';

/*Trazer o nome do livro e o número de páginas dos livros publicados por autores do sexo feminino*/
SELECT NOME_LIVRO, NUMERO_PAGINAS 
FROM LIVROS
WHERE SEXO_AUTOR = 'Feminino';

/*Trazer os valores dos livros das editoras de São Paulo*/
SELECT NOME_LIVRO, VALOR_LIVRO 
FROM LIVROS
WHERE UF_EDITORA = 'SP';

/*Trazer os dados dos autores do sexo masculino que tiveram livros publicados por São Paulo ou Rio de Janeiro (Questão Desafio)*/
SELECT *
FROM LIVROS
WHERE SEXO_AUTOR = 'Masculino'
AND (UF_EDITORA = 'SP' OR UF_EDITORA = 'RJ');