INSERT INTO CLIENTE VALUES ('ALAN', 'M', 'ALAN@GMAIL.COM', '09766738947', '45998065041', 'RUA TOLEDO - PERIOLO - CASCAVEL - PR');
INSERT INTO CLIENTE VALUES ('CIDA', 'F', 'CIDA@GMAIL.COM', '98052128900', '45999926326', 'RUA TOLEDO - PERIOLO - CASCAVEL - PR');
INSERT INTO CLIENTE VALUES ('JULIANE', 'F', NULL, NULL, NULL, 'RUA FLORESTA - RIVIERA - CASCAVEL - PR');

SELECT *
FROM CLIENTE;

UPDATE CLIENTE
SET EMAIL = 'ALISSON@GMAIL.COM'
WHERE NOME = 'ALISSON';

UPDATE CLIENTE
SET EMAIL = 'ALAN@GMAIL.COM'
WHERE NOME = 'ALAN';

UPDATE CLIENTE
SET EMAIL = 'CIDA@GMAIL.COM'
WHERE NOME = 'CIDA';

SELECT *
FROM CLIENTE
WHERE TELEFONE IS NULL;

UPDATE CLIENTE
SET TELEFONE = '4532293734'
WHERE TELEFONE IS NULL;